### ISSUE TITLE
Mark AnyVivo as exited

### ISSUE THREAD

**Issue by alexandon11** [linrock/yclist#12]
The company was sold to Boyd Enterprises in 2014 and continues to operate ongoing. The DBA of the company is Jellyfish Art, so any mention online will be of Jellyfish Art. As the founder, I realize this is an unusual company for YC, so feel free to email info@jellyfishart.com with any questions.

**Comment by linrock** [comment]
updated the name of the company to Jellyfish Art and status to exited, thanks!
