### ISSUE TITLE
Update company name

### ISSUE THREAD

**Issue by mattangriffel** [linrock/yclist#2]
Would love to update the following:

"One Month Rails" to "One Month"
"http://onemonthrails.com" to "https://onemonth.com"
"Learn how to code with the #1 bestselling online class One Month Rails" to "Learn how to code websites, build apps, and grow your business."

A few services I've seen still pull from YC List, and I'd love to see this updated so that I don't have to keep reaching out to each one to get them to update our name and URL.

Thanks!

**Comment by linrock** [comment]
@mattangriffel Np, I just changed the text to what you suggested!
