### ISSUE TITLE
yclist - company to add please

### ISSUE THREAD

**Issue by pwyrod** [linrock/yclist#21]
Hello, would you please add this company to the list? It is funded by YC and was a YC 500 startups boot camp member

AdsOptimal (aka Social Nation, Inc.)

Thank you! 
Patricia 415-505-3134

**Comment by linrock** [comment]
@pwyrod Thanks, added as YC S12 - please let me know if the class year should be changed!

**Comment by pwyrod** [comment]
Thank you that's correct.
Best,
Patricia Wyrod
Founder
Think Create Group


***
415.505.3134

**Comment by linrock** [comment]
:+1:
