### ISSUE TITLE
Can you/we export all the companies to a JSON file and use a static site?

### ISSUE THREAD

**Issue by blairanderson** [linrock/yclist#23]
yclist is kinda neat, but could be super cool if the data was static and people could update with PRs instead of creating issues for changes. 

What do you think about exporting as JSON and I convert to a jekyll(or another static builder) site?

**Comment by blairanderson** [comment]
Just found this https://docs.google.com/spreadsheets/d/1OoT1PjIQHLsBZ955rceXN8Sy2_49fuc_MOl2sTQw_hc/pub

**Comment by linrock** [comment]
@blairanderson yeah, it'd be nice if people could make changes directly with PRs and the updates propagate right away after merging. JSON sounds easy enough to edit

that link is to the public google spreadsheet that's currently used to populate the data on the site

**Comment by linrock** [comment]
Updates via PRs are now possible!

Trying out YAML as the data format for now:
https://github.com/linrock/yclist/tree/master/data/companies

**Comment by blairanderson** [comment]
Awesome!
