### ISSUE TITLE
Qurasense (F1), then W16, not dead

### ISSUE THREAD

**Issue by Sorent** [linrock/yclist#27]
Hi,
There is an error in your list. Qurasense from Fellowship 1 in winter 2015 is not dead, but participated in YC Winter 2016 - and is very much allive!:)
Søren, co-founder of Qurasense

**Comment by linrock** [comment]
Thanks Søren, I updated the status of Qurasense in Fellowship 1. Will move it to YC Winter 2016 after I (or someone else) add the list of companies from W16
