### ISSUE TITLE
InklingMarket has been acquired

### ISSUE THREAD

**Issue by ogiberstein** [linrock/yclist#41]
See their website: http://inklingmarkets.com/

**Comment by grantbow** [comment]
So it says on [their blog](http://blog.inklingmarkets.com/2015/09/inklings-final-chapter.html). They were acquired by [cultivatelabs.com](https://www.cultivatelabs.com/). InklingMarket was in Winter of 2006

**Comment by linrock** [comment]
updated, thanks guys!
