### ISSUE TITLE
Update S13 companies

### ISSUE THREAD

**Issue by callmevlad** [linrock/yclist#7]
- Amulyte - Dead (See website)
- Buttercoin - Dead (http://techcrunch.com/2015/04/06/buttercoin-bitcoin-closing/)
- Datarank - Exited (http://www.geekwire.com/2015/simplymeasured-makes-its-second-acquisition-swoops-up-social-intelligence-platform-datarank/)
- Fanhero - Dead (the current fanhero.com is a different company)
- Graft Concepts - Dead
- Hum - Dead
- Kivo - Dead
- Prim - Dead
- SpoonRocket - Dead (http://techcrunch.com/2016/03/15/spoonrocket-shuts-down/)
- Toutpost - now renamed to Cratejoy (https://www.cratejoy.com/) - An easy way to launch your own subscription business.
- Weilos - Exited (http://techcrunch.com/2015/04/06/weilos-the-yc-backed-weight-loss-startup-has-been-acquired-by-weight-watchers/)

**Comment by linrock** [comment]
@callmevlad Thanks a bunch for all the suggestions man - I updated the site!
