### ISSUE TITLE
Add YC Fellowship companies

### ISSUE THREAD

**Issue by tedmiston** [linrock/yclist#8]
Are you interested in including the YC Fellowship companies in this list?

Fellowship V2 list - http://blog.ycombinator.com/first-fellowship-virtual-demo-day

The V1 list is out there somewhere, but a few quick searches on the YC site and Posthaven didn't turn it up.

**Comment by linrock** [comment]
great idea, thanks! i'll add the fellowship V2 companies and update this issue when i get a chance

**Comment by linrock** [comment]
finally added the fellowship v2 companies!
https://github.com/linrock/yclist/blob/master/data/companies/fellowship.v2.yml
